export const testId = '5122927974398404'


export const ACTIONS = {
    GET_CATEGORIES_WITH_TYPES: 'GET_CATEGORIES_WITH_TYPES',
    GET_SETS: 'GET_SETS',
    CHANGE_FILTERS: 'CHANGE_FILTERS',
    CHANGE_USER: 'CHANGE_USER',
    CHANGE_CATEGORY: 'CHANGE_CATEGORY',
};