export const testId = '5122927974398404'


export const ACTIONS = {
    GET_CATEGORIES_WITH_TYPES: 'GET_CATEGORIES_WITH_TYPES',
    ADD_TO_COLLECTION: 'ADD_TO_COLLECTION',
    ADD_SET_TO_LIST: 'ADD_SET_TO_LIST',
    REMOVE_FROM_COLLECTION: 'REMOVE_FROM_COLLECTION',
    UPDATE_SET_NUMBERS: 'UPDATE_SET_NUMBERS',
    DELETE_SET_AND_NUMBERS: 'DELETE_SET_AND_NUMBERS',
    UPDATE_SET_INFO: 'UPDATE_SET_INFO',
    GET_SETS: 'GET_SETS',
    CHANGE_FILTERS: 'CHANGE_FILTERS',
    CHANGE_USER: 'CHANGE_USER',
    CHANGE_CATEGORY: 'CHANGE_CATEGORY',
};